import os
import vertexai
from vertexai.preview.vision_models import ImageGenerationModel
import logging
from datetime import datetime

logger = logging.getLogger(__name__)

async def generate_image(prompt: str) -> str:
    """
    Generate an image using Google's Imagen model via Vertex AI.
    
    Required environment variables:
    - GOOGLE_CLOUD_PROJECT: Your GCP project ID
    - GOOGLE_APPLICATION_CREDENTIALS: Path to service account JSON (optional if using default credentials)
    """
    try:
        # Get configuration from environment
        project_id = os.getenv("GOOGLE_CLOUD_PROJECT")
        location = os.getenv("GOOGLE_CLOUD_LOCATION", "us-central1")
        
        # Validate required configuration
        if not project_id:
            raise ValueError(
                "GOOGLE_CLOUD_PROJECT environment variable is required for image generation. "
                "Please set it in your .env file or skip image generation."
            )
        
        logger.info(f"Initializing Vertex AI (project: {project_id}, location: {location})")
        
        # Initialize Vertex AI with project configuration
        vertexai.init(project=project_id, location=location)
        
        # Load the Imagen 3 model (latest version)
        logger.info("Loading Imagen model...")
        model = ImageGenerationModel.from_pretrained("imagen-3.0-generate-001")
        
        # Generate image with proper parameters
        logger.info("Generating image (this may take 20-30 seconds)...")
        
        images = model.generate_images(
            prompt=prompt,
            number_of_images=1,
            language="en",
            aspect_ratio="16:9",
            safety_filter_level="block_some",
            person_generation="allow_adult",
        )
        
        # Get the first image from the response
        if not images or len(images) == 0:
            raise ValueError("No images were generated by the model")
        
        image = images[0]
        logger.info("Image generated successfully")
        
        # Create output directory
        output_dir = "generated_images"
        os.makedirs(output_dir, exist_ok=True)
        
        # Create filename with timestamp
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        output_file = os.path.join(output_dir, f"blog_image_{timestamp}.png")
        
        logger.info(f"Saving image to {output_file}...")
        
        # Save the image bytes
        # The image object has _image_bytes attribute or save method
        try:
            image.save(location=output_file, include_generation_parameters=False)
        except AttributeError:
            # Fallback: save using _image_bytes if available
            if hasattr(image, '_image_bytes'):
                with open(output_file, 'wb') as f:
                    f.write(image._image_bytes)
            else:
                raise ValueError("Unable to extract image data from response")
        
        # Verify file exists and has content
        if os.path.exists(output_file):
            file_size = os.path.getsize(output_file)
            if file_size == 0:
                raise ValueError(f"Image file was created but is empty: {output_file}")
            
            logger.info(f"✅ Image saved successfully! File: {output_file}, Size: {file_size:,} bytes")
            
            # Return absolute path
            abs_path = os.path.abspath(output_file)
            return abs_path
        else:
            raise FileNotFoundError(f"Image file was not created at {output_file}")
        
    except ValueError as e:
        # Configuration errors
        logger.error(f"Configuration error: {str(e)}")
        raise
    except Exception as e:
        # Network or API errors
        logger.error(f"Failed to generate/save image: {type(e).__name__}: {str(e)}")
        logger.info("Tip: Check your GCP project settings, credentials, and API enablement")
        raise